dv_saisie:
    resource: "@DVSaisieBundle/Resources/config/routing.yml"
    prefix:   /

dv_calendrier:
    resource: "@DVCalendrierBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
