dv_saisie_homepage:
    path:     /saisie
    defaults: { _controller: DVSaisieBundle:Default:index }

dv_saisie_ok:
    path:     /saisie/succes
    defaults: { _controller: DVSaisieBundle:Default:enregister }
